name: Linters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop checks
      uses: reviewdog/action-rubocop@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        rubocop_version: 0.74
